In [3]:
import pandas as pd
import numpy as np
import requests

In [4]:
poke_url = 'https://pokeapi.co/api/v2/pokemon/'

In [5]:
r2 = requests.get(poke_url)
# r2.json()

In [7]:
pokemon_name_list = [requests.get(poke_url + str(i+1) + '/').json()['name'] for i in range(0, 1010)]

In [8]:
base_stats_list = [j['base_stat'] for i in range(0, 1010) for j in requests.get(poke_url + str(i+1)).json()['stats']]

In [9]:
hp_stat = []
attack_stat = []
defense_stat = []
special_attack_stat = []
special_defense_stat = []
speed_stat = []

for i in range(len(base_stats_list)):
    if i % 6 == 0:
        hp_stat.append(base_stats_list[i])
    elif i % 6 == 1:
        attack_stat.append(base_stats_list[i])
    elif i % 6 == 2:
        defense_stat.append(base_stats_list[i])
    elif i % 6 == 3:
        special_attack_stat.append(base_stats_list[i])
    elif i % 6 == 4:
        special_defense_stat.append(base_stats_list[i])
    else:
        speed_stat.append(base_stats_list[i])

In [10]:
dictionary = {"Pokemon_Name" : pokemon_name_list, "hp" : hp_stat, "attack" : attack_stat, "defense" : defense_stat,
             "special attack" : special_attack_stat, "special defense" : special_defense_stat, "speed" : speed_stat}
pokemon_df = pd.DataFrame(dictionary)
pokemon_df

,Pokemon_Name,hp,attack,defense,special attack,special defense,speed
0,bulbasaur,45,49,49,65,65,45
1,ivysaur,60,62,63,80,80,60
2,venusaur,80,82,83,100,100,80
3,charmander,39,52,43,60,50,65
4,charmeleon,58,64,58,80,65,80
...,...,...,...,...,...,...,...
1005,iron-valiant,74,130,90,120,60,116
1006,koraidon,100,135,115,85,100,135
1007,miraidon,100,85,100,135,115,135
1008,walking-wake,99,83,91,125,83,109
1009,iron-leaves,90,130,88,70,108,104

In [13]:
pokemon_df.to_csv('pokemon_base_stats.csv', index=False)